/*
 * SPI_pri.h
 *
 *  Created on: Sep 24, 2022
 *      Author: Dell
 */

#ifndef MCAL_SPI_SPI_PRI_H_
#define MCAL_SPI_SPI_PRI_H_

/* Data Order Options */
#define MSB_FIRST 0
#define LSB_FIRST 1

#define DATA_ORDER_MASK 0b11011111

/* CLOCK POLARITY */
#define LEADING_RISING_TRAILLING_FALLING 0
#define LEADING_FALLING_TRAILLING_RISING 1

#define CLOCK_POLARITY_MASK 0b11110111

/* CLOCK PHASE */
#define LEADING_SAMPLE_TRAILLING_SETUP 0
#define LEADING_SETUP_TRAILLING_SAMPLE 1

#define CLOCK_PHASE_MASK 0b11111011

/* CLOCK RATE SELECT */
#define SPSR_PRESCALE_4 0
#define SPCR__PRESCALE_4 0
#define SPSR_PRESCALE_16 0
#define SPCR_PRESCALE_16 1
#define SPSR_PRESCALE_64 0
#define SPCR_PRESCALE_64 2
#define SPSR_PRESCALE_128 0
#define SPCR_PRESCALE_128 3

#define SPSR_PRESCALE_2 1
#define SPCR_PRESCALE_2 0
#define SPSR_PRESCALE_8 1
#define SPCR_PRESCALE_8 1
#define SPSR_PRESCALE_32 1
#define SPCR_PRESCALE_32 2
#define SPSR_PRESCALE_64 1
#define SPCR_PRESCALE_64 3

#define CLK_FREQ_MASK_SPCR 0b11111100
#define CLK_FREQ_MASK_SPSR 0b11111110

/* Serial Transfer Complete Interrupt */
void __vector_12(void) __attribute__((signal));
#endif /* MCAL_SPI_SPI_PRI_H_ */
