/*
 * TRANSISTORS_cfg.h
 *
 *  Created on: Aug 25, 2022
 *      Author: Dell
 */

#ifndef HAL_TRANSISTORS_TRANSISTORS_CFG_H_
#define HAL_TRANSISTORS_TRANSISTORS_CFG_H_

#define TRANS0_PORT PORTB_ID
#define TRANS0_PIN PIN7_ID

#define TRANS1_PORT PORTB_ID
#define TRANS1_PIN PIN6_ID

#define TRANS2_PORT PORTB_ID
#define TRANS2_PIN PIN7_ID

#define TRANS3_PORT PORTB_ID
#define TRANS3_PIN PIN6_ID

#endif /* HAL_TRANSISTORS_TRANSISTORS_CFG_H_ */
