/*
 * I2C_pri.h
 *
 *  Created on: Sep 26, 2022
 *      Author: Dell
 */

#ifndef MCAL_I2C_I2C_PRI_H_
#define MCAL_I2C_I2C_PRI_H_

#define MT_START_CONDITION_TRANSMITTED 0x08
#define MT_REPEATED_START_CONDITION_TRANSMITTED 0x10
#define MT_SLA_W_TRANSMITTED_RECEIVED_ACK 0x18
#define MT_SLA_W_TRANSMITTED_RECEIVED_NACK 0x20
#define MT_DATA_TRANSMITTED_RECEIVED_ACK 0x28
#define MT_DATA_TRANSMITTED_RECEIVED_NACK 0x30
#define MT_ARBITRATION_LOST 0x38

#define MR_START_CONDITION_TRANSMITTED 0x08
#define MR_REPEATED_START_CONDITION_TRANSMITTED 0x10
#define MR_ARBITRATION_LOST_ACK 0x38
#define MR_SLA_R_TRANSMITTED_ACK 0x40
#define MR_SLA_R_TRANSMITTED_NACK 0x48
#define MR_DATA_BYTE_RECEIVED_ACK 0x50
#define MR_DATA_BYTE_RECEIVED_NACK 0x58

#endif /* MCAL_I2C_I2C_PRI_H_ */
